todo/todoapp/urls.py
from . import views
from django.urls import path
app_name='todoapp'
urlpatterns=[
    path("",views.add,name='add'),

    path('updat/<int:id>/',views.updat,name='update'),
    path("cbvhome/",views.TaskListview.as_view(),name='cbvhome'),
    path("details/<int:pk>/",views.TaskDetailview.as_view(),name='details'),
    path('update/<int:pk>/',views.TaskUpdateview.as_view(),name='update'),
    path('delete/<int:pk>/',views.TaskDeleteView.as_view(),name='delete')


]

todo/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todo/todoapp/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    objects = None
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name

todo/todoapp/forms.py
from .models import Task
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todo/todoapp/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Task
from .forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView


# Create your views here.
class TaskListview(ListView):
    model = Task
    template_name = 'index.html'
    context_object_name = 'task1'
class TaskDetailview(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'
class TaskUpdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('todoapp:details',kwargs={'pk':self.object.id})
class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')



def add(request):
    task1 = Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('name')
        priority=request.POST.get('priority')
        date=request.POST.get('date')
        task=Task(name=name,priority=priority,date=date)
        task.save()

    return render(request,'index.html',{'task1':task1})
def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method == 'POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')
def updat(request,id):
    task=Task.objects.get(id=id)
    form1=TodoForm(request.POST or None,instance=task)
    if form1.is_valid():
        form1.save()
        return redirect('/')
    return render(request,'edit.html',{'form1':form1,'task':task})




#def details(request):
   # task=Task.objects.all()
 #   return render(request,'details.html',{'task':task})

todo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
 <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todo/templates/delete.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Delete?</p>
    <button type="submit">Confirm</button>
</form>

{% endblock %}

todo/templates/details.html
{% extends 'base.html' %}
{% block content %}
<div class="shadow card">
                    <div class="card-body">
                        <h5 class="card-tittle">{{task.name}}</h5>
                        <p><b>{{task.priority}}</b></p>
                        <p><b>{{task.date}}</b></p>

                        <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                        <a class="btn btn-warning" href="{% url 'todoapp:update' task.id %}">Update</a>

                    </div>
                </div>
{% endblock %}

todo/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form1.as_p}}
    <button type="submit">confirm</button>
</form>

{% endblock %}

todo/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>TODO</h1>
                </div>
            </div>

        </div>

    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
         <form method="post" class="p-3 shadow">
        {% csrf_token %}
             <div class="form-group">
         <input type="text" class="form-control" name="name" placeholder="Enter name">
    </div>
     <div class="form-group">
          <input type="text" class="form-control" name="priority" placeholder="priority">
     </div>
        <div class="form-group">
          <input type="date" class="form-control" name="date" placeholder="Date">
     </div>
    <input type="submit" class="btn btn-success">

              </form>

    </div>
        <div class="col-md-6">
            <h4>Task to be completed</h4>
            {% for i in task1 %}
                <div class="shadow card">
                    <div class="card-body">
                        <h5 class="card-tittle">{{i.name}}</h5>
                        <p><b>{{i.priority}}</b></p>
                        <p><b>{{i.date}}</b></p>

                        <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                        <a class="btn btn-warning" href="{% url 'todoapp:update' i.id %}">Update</a>

                    </div>
                </div>
            {% endfor %}

                </div>
    </div>
    </div>


{% endblock %}

todo/templates/update.html
{% extends 'base.html' %}
{% block content %}

<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">confirm</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}